# Generated by Django 4.0.3 on 2022-04-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0004_alter_worker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
